name: '이슈 생성'
description: '이슈를 예쁘게 써보야옹😺'
title: '"[Convention] 제목" 형식으로 작성해주세요 (예) [Feat] home'
body:
  - type: markdown
    attributes:
      value: |
        |convention|purpose|
        |:---|:---|
        |Feat|새로운 기능 구현|
        |Fix|버그 수정|
        |Refactor|리팩토링|
        |Hotfix|긴급 업데이트|

  - type: input
    id: description
    attributes:
      label: '🎨 Description'
      description: '이슈에 대해 간략히 설명해주세요'
      placeholder: '어떤 기능을 구현하시나요?'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '🥨 Tasks'
      description: '이슈 구현에 필요한 하위 작업들을 작성해주세요'
      value: |
        - [ ] 
    validations:
      required: true
